config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :searches

  resources :doctors do
    member do
      post :create_rating
    end
  end

  resources :hospitals do
    member do
      post :create_rating
    end

    resources :patients do
      member do
        patch :waiting_room_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_pay_patient
        patch :discharge_patient
      end
    end
  end

  resources :medications

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @patients = Patient.all
    @hospitals = Hospital.all
    @medications = Medication.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_searchbars.html.haml
%div.row
  %h4.sidebar

    = form_tag searches_path, method: :get, class: "navbar-form", role: "search" do
      .input-group
        = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Anything"
        .input-group-btn
          %button.btn.btn-default{:style => "width:40px;"}
            %i.glyphicon.glyphicon-search

    / = form_tag hospitals_path, method: :get, class: "navbar-form", role: "search" do
    /   .input-group
    /     = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Hospitals"
    /     .input-group-btn
    /       %button.btn.btn-default{:style => "width:40px;"}
    /         %i.glyphicon.glyphicon-search

    / = form_tag medications_path, method: :get, class: "navbar-form", role: "search" do
    /   .input-group
    /     = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Medications"
    /     .input-group-btn
    /       %button.btn.btn-default{:style => "width:40px;"}
    /         %i.glyphicon.glyphicon-search

/ = form_tag hospital_patients_path(@hospital), method: :get, class: "navbar-form", role: "search" do
/   .input-group
/     = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Patients"
/     .input-group-btn
/       %button.btn.btn-default{:style => "width:40px;"}
/         %i.glyphicon.glyphicon-search

app/views/home/index.html.haml
.container
  .row
    .col-md-6
    .col-md-6.home-index
      %h1.home List of Hospitals
      = link_to "Add Hospital", new_hospital_path
      %ul
        - @hospitals.each do |h|
          %li= h.hospital_name
          = link_to "Show", hospital_path(h)

      %h1.home List of Medications

      = link_to "Add Medication", new_medication_path
      %ul
        - @medications.each do |m|
          %li
            = m.medication_name
            = m.medication_dosage
            = link_to "Show", medication_path(m)