config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :searches

  resources :doctors do
    member do
      post :create_rating
    end
  end

  resources :hospitals do
    member do
      post :create_rating
    end

    resources :patients do
      member do
        patch :waiting_room_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_pay_patient
        patch :discharge_patient
      end
    end
  end

  resources :medications

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :at_least_10
  def at_least_10

    if self.dob
      errors.add(:dob, 'you must be 10 years or older.') if self.dob > 10.years.ago.to_date
    end
  end
  validates :description, presence: true
  validates :gender, presence: true
  validates :bloodtype, presence: true

  BLOODTYPE_OPTIONS = [
    ["A+", "A+"],
    ["A-", "A-"],
    ["B+", "B+"],
    ["B-", "B-"],
    ["AB+", "AB+"],
    ["AB-", "AB-"],
    ["O+", "O+"],
    ["O-", "O-"]
  ]

  has_many :doctors, through: :patient_doctors
  has_many :patient_doctors
  has_many :medications, through: :patient_medications
  has_many :patient_medications
  belongs_to :hospital

  include Workflow
  workflow do
    state :waiting_room do
      event :wait, transitions_to: :waiting_room
      event :exam, transitions_to: :checkup
      event :scan, transitions_to: :xray
      event :operation, transitions_to: :surgery
      event :leave, transitions_to: :discharge
    end

    state :checkup do
      event :exam, transitions_to: :checkup
      event :wait, transitions_to: :waiting_room
      event :scan, transitions_to: :xray
      event :operation, transitions_to: :surgery
      event :pay, transitions_to: :bill_pay
      event :leave, transitions_to: :discharge
    end

    state :xray do
      event :scan, transitions_to: :xray
      event :wait, transitions_to: :waiting_room
      event :exam, transitions_to: :checkup
      event :operation, transitions_to: :surgery
      event :pay, transitions_to: :bill_pay
      event :leave, transitions_to: :discharge
    end

    state :surgery do
      event :operation, transitions_to: :surgery
      event :scan, transitions_to: :xray
      event :wait, transitions_to: :waiting_room
      event :exam, transitions_to: :checkup
      event :pay, transitions_to: :bill_pay
      event :leave, transitions_to: :discharge
    end

    state :bill_pay do
      event :pay, transitions_to: :bill_pay
      event :leave, transitions_to: :discharge
    end

    state :discharge do
      event :leave, transitions_to: :discharge
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :waiting_room_patient,
    :checkup_patient,
    :xray_patient,
    :surgery_patient,
    :bill_pay_patient,
    :discharge_patient
  ]
  def index
    @patients = Patient.all
    @hospital = Hospital.find params[:hospital_id]
  end

  def new
    # @doctors = @patient.doctors
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.new
    @medications = Medication.all
  end

  def create
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.new patient_params
    @medications = Medication.all
    if @patient.save
      flash[:notice] = 'Patient was successfully created'
      redirect_to hospital_patients_path
    else
      flash[:error] = 'Patient was NOT saved.'
      render :new
    end
  end

  def show
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @doctors = @patient.doctors
  end

  def edit
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.find params[:id]
    @doctors = @patient.doctors
    @medications = Medication.all
  end

  def update
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.find params[:id]
    @patient.update_attributes patient_params
    @medications = Medication.all
    redirect_to hospital_patients_path
  end

  def destroy
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.find params[:id]
    @patient.destroy
    redirect_to hospital_patients_path
  end

  def waiting_room_patient
    @patient.wait!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def checkup_patient
    @patient.exam!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def xray_patient
    @patient.scan!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def surgery_patient
    @patient.operation!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def bill_pay_patient
    @patient.pay!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def discharge_patient
    @patient.leave!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def search_results
    @hospital = Hospital.find params[:hospital_id]
    @patients = Patient.where("first_name LIKE ? OR last_name LIKE ? OR description LIKE ? OR dob LIKE ? OR gender LIKE ? OR bloodtype LIKE ? AND hospital_id = ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "params[:hospital_id")
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(
      :id,
      :first_name,
      :last_name,
      :dob,
      :description,
      :gender,
      :bloodtype,
      medication_ids: []
      )
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def patient_current_state?(patient_object)
    patient_object.workflow_state
  end

  def is_patient_waiting_room?(patient_object)
    patient_object.current_state
  end
end

app/views/patients/_form.html.haml
.container
  .row
    .col-md-6
    .col-md-6.patient-form
      %h1 #{params[:action].capitalize} Patient
      = form_for [@hospital, @patient] do |p|
        - if @patient.errors.any?
          - @patient.errors.full_messages.each do |message|
            = message
            %br/
            %br/
        .form-group
          = p.label :first_name
          = p.text_field :first_name, class: "form-control first-name"
          %br/
        .form-group
          = p.label :last_name
          = p.text_field :last_name, class: "form-control last-name"
          %br/
        .form-group
          = p.label :dob
          = p.date_select :dob, :start_year=>1915, :end_year=>2015, class: "form-control date-of-birth"
          %br/
        .form-group
          = p.label :description
          = p.text_field :description, class: "form-control description"
          %br/
        .form-group
          = p.label :gender
          = p.radio_button(:gender, "male")
          = p.label(:gender, "male")
          = p.radio_button(:gender, "female")
          = p.label(:gender, "female")
          %br/
        .form-group
          = p.label :bloodtype
          = p.select :bloodtype, options_for_select(Patient::BLOODTYPE_OPTIONS, p.object.bloodtype), include_blank: "--- Select ---", class: "form-control blood-type"
        %br
        .checkbox
          = hidden_field_tag 'patient[medication_ids][]', ''
          - @medications.each do |med|
            %label
              = check_box_tag 'patient[medication_ids][]', med.id, @patient.medications.include?(med)
              = med.medication_name
        = p.submit "Submit", class: "btn btn-success disabled submit-stuff"
        %br/
        %br/
        = link_to "Cancel", hospital_patients_path, class: "btn btn-danger"



/ %div.container.name
/   %div.row
/     %div.col-md-12

app/views/patients/_patient_list.html.haml
.row
- a = 0
- b = 1
%ul{class: "patient_list"}
  - @patients.each_slice(10) do |row|
    %li{class: "section_#{a+1}"}
      - a = a + 1
      - row.each do |patient|
        .col-md-12
          = link_to patient[:first_name], hospital_patient_path(@hospital, patient)
          = patient.last_name
          %br
%ul{class: "link_list"}
  - a.times do
    %li{class: "link_#{b}"}
      %a{class: "link_#{b}", number: b}
        = "page #{b}"
    - b += 1

app/views/patients/_workflow_patient.html.haml
***
= @patient.workflow_state.upcase
***
= @patient.first_name
= @patient.last_name
= @patient.dob
= @patient.description
= @patient.gender
= @patient.bloodtype
%br
- @hospital = @patient.hospital
- if @patient.waiting_room?
  = link_to "Checkup", 'javascript:void(0);', class: "checkup-patient"
  = link_to "Xray", 'javascript:void(0);', class: "xray-patient"
  = link_to "Surgery", 'javascript:void(0);', class: "surgery-patient"
  = link_to "Discharge", 'javascript:void(0);', class: "discharge-patient"
- if @patient.checkup?
  = link_to "Waiting Room", 'javascript:void(0);', class: "waitingroom-patient"
  = link_to "Xray", 'javascript:void(0);', class: "xray-patient"
  = link_to "Surgery", 'javascript:void(0);', class: "surgery-patient"
  = link_to "Bill Pay", 'javascript:void(0);', class: "billpay-patient"
  = link_to "Discharge", 'javascript:void(0);', class: "discharge-patient"
- if @patient.xray?
  = link_to "Waiting Room", 'javascript:void(0);', class: "waitingroom-patient"
  = link_to "Checkup", 'javascript:void(0);', class: "checkup-patient"
  = link_to "Surgery", 'javascript:void(0);', class: "surgery-patient"
  = link_to "Bill Pay", 'javascript:void(0);', class: "billpay-patient"
  = link_to "Discharge", 'javascript:void(0);', class: "discharge-patient"
- if @patient.surgery?
  = link_to "Waiting Room", 'javascript:void(0);', class: "waitingroom-patient"
  = link_to "Checkup", 'javascript:void(0);', class: "checkup-patient"
  = link_to "Xray", 'javascript:void(0);', class: "xray-patient"
  = link_to "Bill Pay", 'javascript:void(0);', class: "billpay-patient"
  = link_to "Discharge", 'javascript:void(0);', class: "discharge-patient"
- if @patient.bill_pay?
  = link_to "Discharge", 'javascript:void(0);', class: "discharge-patient"

app/views/patients/bill_pay_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")

app/views/patients/checkup_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")

app/views/patients/discharge_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")

app/views/patients/edit.html.haml
= render 'form'

app/views/patients/index.html.haml
.container
  .row
    .col-md-6
    .col-md-6.patient-index
      %input.patient-search{type: "text", placeholder: "Search Patients"}
      %input.hospital-id{type:"hidden", name:"hospital_id", value: @hospital.id}
      %button.patientsearch-button Search

      %h1 List of Patients
      = link_to "Add Patient", new_hospital_patient_path(@hospital)
      
      .rendered-patients
        = render 'patient_list'

app/views/patients/new.html.haml
= render 'form'

app/views/patients/search_results.js.haml
$(".rendered-patients").html("#{j(render 'patient_list')}")

app/views/patients/show.html.haml
/ javascript void, class: "check-patient", patient_id: @patient_id

.container
  = hidden_field_tag 'patient_id', @patient.id
  = hidden_field_tag 'hospital_id', @patient.hospital_id
  .row
    .col-md-6
    .col-md-6.patient-show
      %h1 Current Patient's Information
      %ul
        %li.patientsclass{ class: patient_current_state?(@patient)}
          .some
            =render 'workflow_patient'
      %br
      %br
      %ul
        - @patient.medications.each do |m|
          %li
            =m.medication_name
            =m.medication_dosage
      %br/
      %br/
      = link_to "Edit", edit_hospital_patient_path(@hospital, @patient), class: "btn btn-success"
      = link_to "Delete", hospital_patient_path(@hospital, @patient), method: :delete, class: "btn btn-danger"
      %br/
      %br/
      = link_to "Back", hospital_patients_path, class: "btn btn-danger"

app/views/patients/surgery_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")

app/views/patients/waiting_room_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")

app/views/patients/xray_patient.js.haml
$(".some").html("#{j(render 'workflow_patient')}")