config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :searches

  resources :doctors do
    member do
      post :create_rating
    end
  end

  resources :hospitals do
    member do
      post :create_rating
    end

    resources :patients do
      member do
        patch :waiting_room_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_pay_patient
        patch :discharge_patient
      end
    end
  end

  resources :medications

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients, dependent: :destroy
  has_many :hospital_doctors
  has_many :doctors, through: :hospital_doctors
  has_many :ratings, as: :ratable
  # has_many :medications, through: :patients
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    if !params[:q].blank?
      @hospitals = Hospital.where("hospital_name LIKE ?", "%#{params[:q]}%")
    else
      @hospitals = Hospital.all
    end
  end

  def new
    @doctors = Doctor.all
    @hospital = Hospital.new
    @doctor = Doctor.new

    # @doctors = @patient.doctors
  end

  def create
    @hospital = Hospital.create hospital_params
    redirect_to root_path
  end

  def create_rating
    @hospital = Hospital.find params[:id]
    @rating = @hospital.ratings.create rating_params
    redirect_to hospital_path(@hospital)
  end

  def show
    @hospital = Hospital.find params[:id]
    @doctors = @hospital.doctors
    @ratings = @hospital.ratings
    @rating = Rating.new
  end

  def edit
    @doctors = Doctor.all
    @hospital = Hospital.find params[:id]
    # @doctors = @patient.doctors
  end

  def update
    @hospital = Hospital.find params[:id]
    @hospital.update_attributes hospital_params
    redirect_to root_path
  end

  def destroy
    @hospital = Hospital.find params[:id]
    @hospital.destroy
    redirect_to root_path
  end

  private
  def hospital_params
    params.require(:hospital).permit(
      :hospital_name,
      doctor_ids: [],
      hospital_ids: []
      )
  end

  def rating_params
    params.require(:rating).permit(
      :score,
      :comment,
      :ratable_id,
      :ratable_type
    )
  end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.haml
.container
  .row
    .col-md-6
    .col-md-6.hospital-new
      %h1 #{params[:action].capitalize} Hospital
      = form_for @hospital do |p|
        - if @hospital.errors.any?
          - @hospital.errors.full_messages.each do |message|
            = message
            %br/
            %br/
        = p.label :hospital_name
        = p.text_field :hospital_name
        %br/
        - @doctors.each do |d|
          = check_box_tag 'hospital[doctor_ids][]', d.id, @hospital.doctors.include?(d)
          = d.name
        %br/
        = p.submit
        %br/
        %br/
        = link_to "Cancel", :back, class: "btn btn-danger"

app/views/hospitals/edit.html.haml
%h1 Edit Current Hospital Information
= render 'form'

app/views/hospitals/index.html.haml
%h1 List of Hospitals
= link_to "Add Hospital", new_hospital_path
%ul
  - @hospitals.each do |h|
    %li= h.hospital_name

app/views/hospitals/new.html.haml
= render 'form'

app/views/hospitals/show.html.haml
.container
  .row
    .col-md-6
    .col-md-6.show-hospital
      %h1 Hospital
      %strong
        %h2= @hospital.hospital_name
      %br/
      = link_to "View Patients", hospital_patients_path(@hospital)
      %br/
      %br/
      = link_to "Edit", edit_hospital_path(@hospital), class: "btn btn-success"
      = link_to "Delete", hospital_path(@hospital), method: :delete, class: "btn btn-danger"
      %br/
      %br
      - @ratings.each do |r|
        = r.score
        = r.comment
        %br
      = form_for @rating, url: create_rating_hospital_path(@hospital) do |f|
        = f.label :score
        = f.text_field :score
        %br/
        = f.label :comment
        = f.text_area :comment
        %br/
        = f.submit