config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :searches

  resources :doctors do
    member do
      post :create_rating
    end
  end

  resources :hospitals do
    member do
      post :create_rating
    end

    resources :patients do
      member do
        patch :waiting_room_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_pay_patient
        patch :discharge_patient
      end
    end
  end

  resources :medications

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :patients, through: :patient_doctors
  has_many :hospitals, through: :hospital_doctors
  has_many :patient_doctors
  has_many :hospital_doctors
  has_many :ratings, as: :ratable

  # def self.search(search)
  #   if !params[:q].blank?
  #       @doctors = Doctor.where("name LIKE ? OR practice LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
  #   else
  #     @doctors = Doctor.all
  #   end
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    if !params[:q].blank?
      @doctors = Doctor.where("name LIKE ? OR practice LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @doctors = Doctor.all
    end
  end

  def new
    @doctor = Doctor.new
    @patients = Patient.all
    @hospitals = Hospital.all
  end

  def create
    @doctor = Doctor.create doctor_params
    redirect_to doctors_path
  end

  def create_rating
    @doctor = Doctor.find params[:id]
    @rating = @doctor.ratings.create rating_params
    redirect_to doctor_path(@doctor)
  end

  def show
    @rating = Rating.new
    @doctor = Doctor.find params[:id]
    @ratings = @doctor.ratings
  end

  def edit
    @doctor = Doctor.find params[:id]
    @patients = Patient.all
    @hospitals = Hospital.all
  end

  def update
    @doctor = Doctor.find params[:id]
    @doctor.update_attributes doctor_params
    redirect_to doctor_path(@doctor)
  end

  def destroy
    @doctor = Doctor.find params[:id]
    @doctor.delete
    redirect_to doctors_path
  end

  private
  def doctor_params
    params.require(:doctor).permit(
      :name,
      :practice,
      :doctorable_id,
      :doctorable_type,
      doctor_ids: [],
      hospital_ids: []
    )
  end

  def rating_params
    params.require(:rating).permit(
      :score,
      :comment,
      :ratable_id,
      :ratable_type
    )
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
.container
  .row
    .col-md-6
    .col-md-6.doctor-form
      %h1 #{params[:action].capitalize} Doctor
      = form_for @doctor do |d|
        - if @doctor.errors.any?
          - @doctor.errors.full_messages.each do |message|
            = message
            %br
        = d.label :name
        = d.text_field :name
        %br
        = d.label :practice
        = d.text_field :practice
        %br
        - @hospitals.each do |p|
          = check_box_tag 'doctor[hospital_ids][]', p.id, @doctor.hospitals.include?(p)
          = p.hospital_name
          %br
        = d.submit

      = link_to "Cancel", :back, class: "btn btn-danger"

app/views/doctors/edit.html.haml
= render 'form'

app/views/doctors/index.html.haml
.container
  .row
    .col-md-6
    .col-md-6.doc-index
      %h1.doctor-show List of Doctors
      = link_to "Add Doctor", new_doctor_path\
      %br
      %br
      - @doctors.each do |doctor|
        = doctor.name
        %br
        = doctor.practice
        %br
        = link_to "View Doctor", doctor_path(doctor)
        %br
        %br
      = link_to "Back", :back, class: "btn btn-danger"

app/views/doctors/new.html.haml
= render 'form'

app/views/doctors/show.html.haml
.container
  .row
    .col-md-6
    .col-md-6.view-doc
      %h1 Doctor Information
      = @doctor.name
      %br
      = @doctor.practice
      %br
      %br
      = link_to "Edit", edit_doctor_path(@doctor), class: "btn btn-success"
      = link_to "Delete", doctor_path(@doctor), method: :delete, class: "btn btn-danger"
      %br
      %br
      - @ratings.each do |r|
        = r.score
        = r.comment
        %br
      = form_for @rating, url: create_rating_doctor_path(@doctor) do |f|
        = f.label :score
        = f.text_field :score
        %br
        = f.label :comment
        = f.text_area :comment
        %br
        = f.submit
        %br
        = link_to "Back", doctors_path, class: "btn btn-danger"